config/routes.rb
SevenHills::Application.routes.draw do
  root 'pages#home'

  get '/home', to: 'pages#home'
  get '/tandem', to: 'pages#tandem'
  get '/iad', to: 'pages#iad'
  get '/experienced', to: 'pages#experienced'
  get '/pricing', to: 'pages#pricing'
  get '/faq', to: 'pages#faq'
  get '/testimonials', to: 'pages#testimonials'
  get '/facilities', to: 'pages#facilities'
  get '/contact', to: 'pages#contact'
  get '/about', to: 'pages#about'
  get '/members', to: 'users#index'
  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/continuing', to: 'pages#continuing'
  get '/set_member', to: 'users#set_member'
  post '/set_member', to: 'users#member_authentication'
  patch '/set_member', to: 'users#member_authentication'

  resources :posts, only: [:new, :create, :edit, :update]
  resources :users, only: [:create, :edit, :show]
  resources :shifts
  resources :reservations, only: [:new, :create, :show, :index] do
    collection do
      get '/search', to: 'reservations#find'
      post '/search', to: 'reservations#search'
    end
  end

  get '/reservations_home', to: 'reservations#home'
  resources :students, only: [:new, :create]
  resources :openings, only: [:index, :show] do
    collection do
      get '/reserve', to: 'openings#find_reservation'
      post '/reserve', to: 'openings#save_reservation'
      post '/search', to: 'openings#search'
      get '/find_roster', to: 'openings#find_roster'
      post '/roster', to: 'openings#roster'
    end
  end
  namespace :admin do
    resources :openings, only: [:new, :create, :edit, :update, :destroy] do
      collection do
        post '/copy', to: 'openings#copy'
      end
    end
    post 'confirm/:id', to: "students#confirm"
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
	PASSWORD = "Hillspw2"

  has_many :posts
  has_many :shifts
  has_many :reservations

  has_secure_password validations: false

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, uniqueness: true
  validates :password,
    presence: true,
    on: :create,
    length: { minimum: 5 }

  def member?
  	self.member
  end

  def admin?
    self.admin
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, except: [:new, :create]


	def index
		if logged_in?
		  @posts = Post.all.sort_by{ |x| x.updated_at}.reverse
		  @shifts = Shift.all.sort_by{ |x| x.updated_at}.reverse
		else
			redirect_to reservations_home_path
		end
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)

		if @user.save
			session[:user_id] = @user.id
			flash[:notice] = "Thanks for registering! If you're a member, click the link at the bottom of the screen."
			redirect_to reservations_home_path
		else
			render :new
		end
	end

	def show
	end

	def edit
	end

	def update
	end

	def set_member
	end

	def member_authentication
		if params[:member] == User::PASSWORD 
			@user.member = true
			if @user.save
			  flash[:notice] = "You are now saved as a member and have edit capabilities for the schedule."
			  redirect_to '/members'
			else
				flash[:error] = "Incorrect Password"
	  		redirect_to set_member_path
	  	end
  	end
	end

  private

  def set_user
  	@user = User.find_by(id: session[:user_id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :phone, :age, :street_address, :city, :state)
  end

end

app/views/users/_form.html.erb
<div class='well'>
	<%= form_for @user do |f| %>
		<%= render 'shared/errors', obj: @user %>
		<div class='form-group'>
			<%= f.label :first_name %>
			<%= f.text_field :first_name, class: "form-control", placeholder: "First Name" %>
		</div>
		<div class='form-group'>
			<%= f.label :last_name %>
			<%= f.text_field :last_name, class: "form-control", placeholder: "Last Name" %>
		</div>
		<div class='form-group'> 
			<%= f.label :email %>
			<%= f.email_field :email, class: "form-control", placeholder: "example@gmail.com" %>
		</div>
		<div class='form-group'>
			<%= f.label :password %>
			<%= f.password_field :password, class: "form-control" %>
		</div>
		<%= f.submit @user.new_record? ? "Register" : "Update Profile", class: 'btn btn-success' %>
	<% end %>
</div>

app/views/users/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-10 col-sm-offset-1">
      <h3>Edit Your Profile</h3>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">

<div>
	<ul class="list-inline">
		<li>
			<%= link_to(shifts_path, class: "btn btn-primary") do %>
			  View Shift Calendar
			<% end %>
		</li>
		<% unless @user.member? %>
			<li>
				<%= link_to(set_member_path, class: "btn btn-success") do %>
				  Set yourself as a Member
				<% end %>
			</li>
		<% end %>
	</ul>
</div>

<% if @user.member? %>
	<div>
		<ul class="list-inline">
			<li>
				<%= link_to(new_shift_path, class: "btn btn-success") do %>
				  Create a Shift
				<% end %>
			</li>
			<li>
				<%= link_to(new_post_path, class: "btn btn-success") do %>
				  New Post
				<% end %>
			</li>
		</ul>
	</div>
<% end %>

<ul class='nav nav-tabs'>
  <li class="<%= 'active' if params[:tab].nil? %>">
    <%= link_to "New Posts", members_path %>
  </li>
  <li class="<%= 'active' if params[:tab] == 'shifts' %>">
    <%= link_to "New Shifts", members_path(tab: 'shifts') %>
  </li>
</ul>
<br/>

<% if params[:tab].nil? %>
  <% @posts.each do |post| %>
    <div class="well">
			<ul class="list-inline">
			  <li><h3><%= post.title %></h3></li>
			  <li>Posted by: <%= post.creator.first_name %></li>
			  <% if logged_in? && current_user == post.creator %>
			  	<li><%= link_to "Edit", edit_post_path(post) %></li>
			  <% end %>
		  </ul>
	  <p><%= simple_format h(post.body) %></p>
	</div>
  <% end %>
<% elsif params[:tab] == 'shifts' %>
  <% @shifts.each do |shift| %>
    <div class="well">
	  	<% if shift.role == "Tandem Student Count" || shift.role == "IAD Student Count" %>
	  	  <strong><%= shift.creator.first_name %></strong> updated the <strong><%= shift.role %></strong> on <%= display_day(shift.date) %> to <strong><%= shift.person %></strong> students.
	  	<% else %>
		  	<strong><%= shift.person %></strong> signed up for a shift as a <strong><%= shift.role %></strong> on <%= display_day(shift.date) %> from <%= display_time(shift.start_time) %> to <%= display_time(shift.end_time) %>.
		  <% end %>
    </div>
  <% end %>
<% end %>
</div>

app/views/users/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-10 col-sm-offset-1">
      <h3>Register!</h3>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/users/set_member.erb
<div class="well">
	<%= form_for @user, url: {action: "set_member"} do |f| %>
		<%= render 'shared/errors', obj: @user %>
    <div class='form-group'>
    	<%= label_tag "Member Password" %>
    	<%= password_field_tag :member, params[:member] || '' %>
    </div>
    <%= f.submit "Submit", class: 'btn btn-success' %>
	<% end %>
</div>

app/views/users/show.html.erb
<div class="container">
	<h3><%= @user.first_name %> <%= @user.last_name %></h3>
	<% @user.shifts.each do |shift| %>
    <div class="well">
	  	<% if shift.role == "Tandem Student Count" || shift.role == "IAD Student Count" %>
	  	  <strong><%= shift.creator.first_name %></strong> updated the <strong><%= shift.role %></strong> on <%= display_day(shift.date) %> to <strong><%= shift.person %></strong> students.
	  	<% else %>
		  	<strong><%= shift.person %></strong> signed up for a shift as a <strong><%= shift.role %></strong> on <%= display_day(shift.date) %> from <%= display_time(shift.start_time) %> to <%= display_time(shift.end_time) %>.
		  <% end %>
    </div>
  <% end %>
  <div class="well"><ul>
  	<h4>Your Reservations:</h4>
	  <% @user.reservations.each do |res| %>
		  <li><%= link_to "#{res.instruction}", reservation_path(res), class: "btn btn-primary" %></li>
	  <% end %>
	</ul></div>
</div>