config/routes.rb
SevenHills::Application.routes.draw do
  root 'pages#home'

  get '/home', to: 'pages#home'
  get '/tandem', to: 'pages#tandem'
  get '/iad', to: 'pages#iad'
  get '/experienced', to: 'pages#experienced'
  get '/pricing', to: 'pages#pricing'
  get '/faq', to: 'pages#faq'
  get '/testimonials', to: 'pages#testimonials'
  get '/facilities', to: 'pages#facilities'
  get '/contact', to: 'pages#contact'
  get '/about', to: 'pages#about'
  get '/members', to: 'users#index'
  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/continuing', to: 'pages#continuing'
  get '/set_member', to: 'users#set_member'
  post '/set_member', to: 'users#member_authentication'
  patch '/set_member', to: 'users#member_authentication'

  resources :posts, only: [:new, :create, :edit, :update]
  resources :users, only: [:create, :edit, :show]
  resources :shifts
  resources :reservations, only: [:new, :create, :show, :index] do
    collection do
      get '/search', to: 'reservations#find'
      post '/search', to: 'reservations#search'
    end
  end

  get '/reservations_home', to: 'reservations#home'
  resources :students, only: [:new, :create]
  resources :openings, only: [:index, :show] do
    collection do
      get '/reserve', to: 'openings#find_reservation'
      post '/reserve', to: 'openings#save_reservation'
      post '/search', to: 'openings#search'
      get '/find_roster', to: 'openings#find_roster'
      post '/roster', to: 'openings#roster'
    end
  end
  namespace :admin do
    resources :openings, only: [:new, :create, :edit, :update, :destroy] do
      collection do
        post '/copy', to: 'openings#copy'
      end
    end
    post 'confirm/:id', to: "students#confirm"
  end
  
end

app/models/shift.rb
class Shift < ActiveRecord::Base
	include SimpleCalendar

	belongs_to :creator, class_name: 'User', foreign_key: :user_id

	validates :role, presence: true
	validates :date, presence: true
	validates :start_time, presence: true
	validates :end_time, presence: true
	validates :person, presence: true

	scope :by_month, lambda { |year, month| where("date >= ? and date <= ?", "#{year}-#{month}-01", "#{year}-#{month}-31") }

	ROLE_TYPES = ["Pilot", "Tandem Instructor", "IAD Instructor", "Coach"]

  def start_time
  	date
  end

end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController
  before_action :require_member, except: [:index]

  def index
    @shifts = Shift.all
  end

  def new
    @shift = Shift.new
  end

  def create
    @shift = Shift.new(shift_params)
    @shift.creator = current_user
    if @shift.save
      flash[:notice] = "Your shift was saved"
      redirect_to shifts_path
    else
      render :new
    end
  end

  def edit
    @shift = Shift.find(params[:id])
  end

  def update
    @shift = Shift.find(params[:id])
    if @shift.update(shift_params)
      flash[:notice] = "The shift was updated"
      redirect_to shifts_path
    else
      render :edit
    end
  end

  def show
    @shift = Shift.find(params[:id])
  end

  def destroy
    @shift = Shift.find(params[:id])
    @shift.destroy
    flash[:notice] = "The shift was deleted"
    redirect_to shifts_path
  end

  private

  def shift_params
    params.require(:shift).permit!
  end

end

app/views/shifts/_form.html.erb
<div class="well">
	<%= form_for @shift do |f| %>
	  <%= render 'shared/errors', obj: @shift %>
	  <div class='form-group'%>
	  	<%= f.label "Which Role?" %>
	  	<%= f.select(:role, Shift::ROLE_TYPES)%>
	  </div>
	  <div class='form-group'%>
	  	<%= f.label "Who will be working this shift?" %>
	  	<%= f.text_field :person, class: "form-control", placeholder: "Name" %>
	  </div>
	  <div class='form-group'%>
	  	<%= f.label "Date and Start Time:" %>
	  	<%= f.datetime_select :date, {minute_step: 15, ampm: true}%>
	  </div>
	  <div class='form-group'%>
	  	<%= f.label :end_time %>
	  	<%= f.time_select :end_time, {minute_step: 15, ampm: true} %>
	  </div>
	  <div class='form-group'%>
	  	<%= f.label :notes %>
	  	<%= f.text_area :notes, class: "form-control", rows: "3", placeholder: "Enter any notes here, such as having a flexible schedule or strict commitments" %>
	  </div>
	  <%= f.submit(@shift.new_record? ? "Create Shift" : "Update Shift", class: 'btn btn-primary') %>
	<% end %>
</div>

app/views/shifts/edit.html.erb
<h4>Edit your shift</h4>

<%= render 'form' %>

app/views/shifts/index.html.haml
.container
  %h2 Shift Calendar

- if logged_in? 
  .container
    = link_to(new_shift_path, class: "btn btn-success") do 
      Create a Shift

.container
  = calendar @shifts do |shift| 
    %div
      - case shift.role 
      - when "Pilot"
        = link_to(shift_path(shift), class: "calendar-btn cal-teal") do 
          #{shift.role}: #{shift.person}  #{display_time(shift.date)} - #{display_time(shift.end_time)}
      - when "Tandem Instructor"
        = link_to(shift_path(shift), class: "calendar-btn cal-blue") do 
          #{shift.role}: #{shift.person}  #{display_time(shift.date)} - #{display_time(shift.end_time)}
      - when "IAD Instructor"
        = link_to(shift_path(shift), class: "calendar-btn cal-green") do 
          #{shift.role}: #{shift.person}  #{display_time(shift.date)} - #{display_time(shift.end_time)}
      - when "Coach"
        = link_to(shift_path(shift), class: "calendar-btn cal-orange") do
          #{shift.role}: #{shift.person}  #{display_time(shift.date)} - #{display_time(shift.end_time)}

%hr
  %h4 Legend
  %p.center.calendar-btn.cal-blue Tandem Instructor
  %p.center.calendar-btn.cal-green IAD Instructor
  %p.center.calendar-btn.cal-teal Pilot
  %p.center.calendar-btn.cal-orange Coach

app/views/shifts/new.html.erb
<div class="container">
	<h4>Create a Shift<h4>

  <%= render 'form' %>
</div>

app/views/shifts/show.html.erb
<div class="container">	
	<ul class="list-inline">
		<li><h4><%= @shift.role %>: <%= @shift.person %></h4></li>
		<li><%= link_to "Edit", edit_shift_path(@shift) %></li>
		<li><%= link_to "Delete", shift_path(@shift), confirm: "Are you sure you want to delete this shift?", method: :delete %></li>
	</ul>
	<div class="well">
		<p>
			<%= display_day(@shift.date) %>
			from <%= display_time(@shift.date) %> to <%= display_time(@shift.end_time) %>
	  </p>
	  <p>
			Created by: <%= @shift.creator.first_name %> <%= @shift.creator.last_name %>
		</p>
		<p>
			Notes: <%= @shift.notes %>
		</p>
	</div>
</div>