config/routes.rb
SevenHills::Application.routes.draw do
  root 'pages#home'

  get '/home', to: 'pages#home'
  get '/tandem', to: 'pages#tandem'
  get '/iad', to: 'pages#iad'
  get '/experienced', to: 'pages#experienced'
  get '/pricing', to: 'pages#pricing'
  get '/faq', to: 'pages#faq'
  get '/testimonials', to: 'pages#testimonials'
  get '/facilities', to: 'pages#facilities'
  get '/contact', to: 'pages#contact'
  get '/about', to: 'pages#about'
  get '/members', to: 'users#index'
  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/continuing', to: 'pages#continuing'
  get '/set_member', to: 'users#set_member'
  post '/set_member', to: 'users#member_authentication'
  patch '/set_member', to: 'users#member_authentication'

  resources :posts, only: [:new, :create, :edit, :update]
  resources :users, only: [:create, :edit, :show]
  resources :shifts
  resources :reservations, only: [:new, :create, :show, :index] do
    collection do
      get '/search', to: 'reservations#find'
      post '/search', to: 'reservations#search'
    end
  end

  get '/reservations_home', to: 'reservations#home'
  resources :students, only: [:new, :create]
  resources :openings, only: [:index, :show] do
    collection do
      get '/reserve', to: 'openings#find_reservation'
      post '/reserve', to: 'openings#save_reservation'
      post '/search', to: 'openings#search'
      get '/find_roster', to: 'openings#find_roster'
      post '/roster', to: 'openings#roster'
    end
  end
  namespace :admin do
    resources :openings, only: [:new, :create, :edit, :update, :destroy] do
      collection do
        post '/copy', to: 'openings#copy'
      end
    end
    post 'confirm/:id', to: "students#confirm"
  end
  
end

app/models/opening.rb
class Opening < ActiveRecord::Base

	attr_reader :reserved

	validates_presence_of :date, :time, :instruction

	INSTRUCTION_TYPES = ["Tandem", "Instructor Assisted Deployment"]

	default_scope { order("time")}
	scope :open, -> { where(reserved: false)}
	scope :reserved, -> { where(reserved: true)}
	scope :tandem, -> { where(instruction: "Tandem")}
	scope :iad, -> { where(instruction: "Instructor Assisted Deployment")}

	def start_time
		date
	end

	def self.search_by_date(search_date)
		return [] if search_date.blank?
		start_of_day = DateTime.strptime(search_date, "%m/%d/%Y").beginning_of_day
		end_of_day = DateTime.strptime(search_date, "%m/%d/%Y").end_of_day
		Opening.where("date >= ? AND date <= ?", start_of_day, end_of_day)
	end

	def student
		Student.find(student_id)
	end
end

app/controllers/admin/openings_controller.rb
class Admin::OpeningsController < AdminsController
	def new
		@opening = Opening.new
	end

	def create
		@opening = Opening.new(opening_params)
		@opening.date = params[:opening][:date].nil? ? Time.now.to_date : (DateTime.strptime(params[:opening][:date], "%m/%d/%Y")).to_date #Time zone offset
		if @opening.save
			flash[:notice] = "Opening on #{@opening.date.to_date} at #{@opening.time.strftime "%H:%M"} was created."
			redirect_to new_admin_opening_path
		else
			flash[:danger] = "Please pick a date."
			render :new
		end
	end

	def copy
		@old_opening = Opening.find(params[:opening_id])
		if @old_opening.reserved?
			flash[:danger] = "That opening is already reserved and cannot be copied."
			redirect_to opening_path(@old_opening)
		else
			@new_opening = Opening.new(date: @old_opening.date, time: @old_opening.time, instruction: @old_opening.instruction)
			@new_opening.save
			flash[:notice] = "Opening copied successfully!"
			redirect_to opening_path(@new_opening)
		end
	end

	def edit
		@opening = Opening.find(params[:id])
	end

	def update
		@opening = Opening.find(params[:id])
		if @opening.update(opening_params)
			flash[:notice] = "This opening was updated."
		  redirect_to opening_path(@opening)
		else
			flash[:danger] = "This opening could not be updated. Please delete and create a new one."
			render :edit
		end
	end

	def destroy
		opening = Opening.find(params[:id])
		opening.destroy
		flash[:notice] = "Opening was deleted."
		redirect_to openings_path
	end
	
	private

	def opening_params
		params.require(:opening).permit(:instruction, :time)
	end
end

app/controllers/openings_controller.rb
class OpeningsController < ApplicationController
	before_action :require_member, only: [:find_roster, :search_roster, :roster]

	def index
		@openings = Opening
	end

	def show
		@opening = Opening.find(params[:id])
	end

	def find_reservation
		@student = Student.find(params[:student_id])
	end

	def save_reservation
		@opening = Opening.find(params[:opening_id])
		@student = Student.find(params[:student_id])
		@opening.student_id = @student.id
		@opening.reserved = true
		if @opening.save
			AppMailer.send_registration_email(@student).deliver
			flash[:notice] = "You've been added to the reservation and a confirmation email has been sent."
			redirect_to reservation_path(@student.reservations.last)
		else
			flash[:danger] = "Something went wrong. Please try again"
			render :search
		end
	end

	def search
		@student = Student.find(params[:student_id])
		if params[:date].empty?
			flash[:danger] = "Please choose a date below."
			redirect_to reserve_openings_path student_id: @student.id
		else
			@reservation = @student.reservations.last
			if @reservation.instruction == "Tandem"
				@openings = Opening.search_by_date(params[:date]).tandem.open
			elsif @reservation.instruction == "Instructor Assisted Deployment"
				@openings = Opening.search_by_date(params[:date]).iad.open
			end
		end
	end

	def find_roster
	end

	def roster
		@date = params[:date]
		@openings = Opening.search_by_date(@date)
		@tandem_openings = @openings.tandem.reserved
		@iad_openings = @openings.iad.reserved
		@unfilled_openings = @openings.open
	end
end

app/views/admin/openings/edit.html.haml
.container
  .row
    .col-sm-4.col-sm-offset-1
      %h3 Edit Opening
      %h3 Date: #{display_day(@opening.date)}
      %p If you want to change the date, please delete this opening and create a new one.
      = bootstrap_form_for [:admin, @opening] do |f|
        %fieldset
          = f.select(:instruction, Reservation::INSTRUCTION_TYPES)
          = f.time_select :time, {minute_step: 15, ampm: true}
        %fieldset.actions.control-group
          .controls
            = f.submit "Update Opening", class: "btn btn-primary", method: :patch

app/views/admin/openings/new.html.haml
.container
  .row
    .col-sm-4.col-sm-offset-1
      %h3 Create an Opening
      = bootstrap_form_for [:admin, @opening] do |f|
        %fieldset
          = f.select(:instruction, Reservation::INSTRUCTION_TYPES)
          = f.text_field :date, class: "datepicker"
          = f.time_select :time, {minute_step: 15, ampm: true}
        %fieldset.actions.control-group
          .controls
            = f.submit "Create Opening", class: "btn btn-primary"

app/views/admin/openings/show.html.haml
.container
  .row
    .col-sm-10.col-sm-offset-1
      %h3 Type: #{@opening.instruction} 
      %h5 Date: #{display_day(@opening.date)}
      %h5 Time: #{display_time(@opening.time)}
  .row
    .col-sm-10.col-sm-offset-1
      = link_to "Edit Opening", edit_admin_opening_path(@opening), class: "btn btn-primary"
      = link_to "Delete Opening", admin_opening_path(@opening), method: :delete, confirm: "Are you sure you want to delete this opening?", class: "btn btn-danger"