config/routes.rb
SevenHills::Application.routes.draw do
  root 'pages#home'

  get '/home', to: 'pages#home'
  get '/tandem', to: 'pages#tandem'
  get '/iad', to: 'pages#iad'
  get '/experienced', to: 'pages#experienced'
  get '/pricing', to: 'pages#pricing'
  get '/faq', to: 'pages#faq'
  get '/testimonials', to: 'pages#testimonials'
  get '/facilities', to: 'pages#facilities'
  get '/contact', to: 'pages#contact'
  get '/about', to: 'pages#about'
  get '/members', to: 'users#index'
  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/continuing', to: 'pages#continuing'
  get '/set_member', to: 'users#set_member'
  post '/set_member', to: 'users#member_authentication'
  patch '/set_member', to: 'users#member_authentication'

  resources :posts, only: [:new, :create, :edit, :update]
  resources :users, only: [:create, :edit, :show]
  resources :shifts
  resources :reservations, only: [:new, :create, :show, :index] do
    collection do
      get '/search', to: 'reservations#find'
      post '/search', to: 'reservations#search'
    end
  end

  get '/reservations_home', to: 'reservations#home'
  resources :students, only: [:new, :create]
  resources :openings, only: [:index, :show] do
    collection do
      get '/reserve', to: 'openings#find_reservation'
      post '/reserve', to: 'openings#save_reservation'
      post '/search', to: 'openings#search'
      get '/find_roster', to: 'openings#find_roster'
      post '/roster', to: 'openings#roster'
    end
  end
  namespace :admin do
    resources :openings, only: [:new, :create, :edit, :update, :destroy] do
      collection do
        post '/copy', to: 'openings#copy'
      end
    end
    post 'confirm/:id', to: "students#confirm"
  end
  
end

app/views/layouts/_footer.html.erb
<hr class="featurette-divider">

<div class="container">
	<h6 style="text-align:center">
		<small>
			© 2013  Copyright all pages by Seven Hills Skydivers of Madison, WI.  PO Box 8261  Madison, Wisconsin  53708
			All rights reserved.  Unauthorized duplication or publication of any materials from this Site is expressly prohibited.
		</small>
	</h6>
</div>

app/views/layouts/_messages.html.erb
<div class="container">
	<% flash.each do |name, msg| %>
	  <% if msg.is_a?(String) %>
	    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
	      <a class="close" data-dismiss="alert">&#215;</a>
	      <%= content_tag :div, msg, :id => "flash_#{name}" %>
	    </div>
	  <% end %>
	<% end %>
</div>

app/views/layouts/_navigation.html.erb
<div class="navbar-header">
  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </button>
  <a class="navbar-brand" href="/home">Seven Hills Skydivers</a>
</div>
<div class="collapse navbar-collapse">
  <ul class="nav navbar-nav">
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">Skydive <b class="caret"></b></a>
      <ul class="dropdown-menu">
        <li><%= link_to "Tandem", tandem_path %></li>
        <li><%= link_to "Instructor-Assisted Deployment", iad_path %></li>
        <li><%= link_to "Continuing Students", continuing_path %></li>
        <li><%= link_to "Experienced Skydivers", experienced_path %></li>
        <li class="divider"></li>
        <li><%= link_to "Book A Skydive", reservations_home_path %></li>
        <li><%= link_to "Pricing", pricing_path %></li>
        <li><%= link_to "FAQs", faq_path %></li>
        <li><%= link_to "Testimonials", testimonials_path %></li>
      </ul>
    </li>
    <li><%= link_to "About", about_path %></li>
    <li><%= link_to "Facilities", facilities_path %></li>
    <li><%= link_to "Contact", contact_path %></li>
    <% if member? %>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Members <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><%= link_to "Member's Home", members_path %></li>
          <li><%= link_to "Shifts Calendar", shifts_path %></li>
          <li><%= link_to "Roster", find_roster_openings_path %></li>
          <li><%= link_to "Student Reservations", openings_path %></li>
        </ul>
      </li>
    <% end %>
    <% if admin? %>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Admin <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><%= link_to "Create an Opening", new_admin_opening_path %></li>
          <li><%= link_to "Roster", find_roster_openings_path %></li>
          <li><%= link_to "Manage Openings", openings_path %></li>
        </ul>
      </li>
    <% end %>
  </ul>
  <ul class="nav navbar-nav pull-right">
    <% if logged_in? %>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.first_name %> <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li>
            <%= link_to "Profile", user_path(current_user) %>
          </li>
          <li class="divider"></li>
          <li>
            <%= link_to "Logout", logout_path %>
          </li>
        </ul>
      </div>
    <% else %>
      <li><%= link_to "Register", register_path %></li>
      <li><%= link_to "Login", login_path %></li>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">
  <%= metamagic %>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
  <body>
    <header>
      <div class="navbar-wrapper">
        <div class="container">
          <div class="navbar navbar-inverse navbar-static-top" role="navigation">
            <div class="container">
              <%= render 'layouts/navigation' %>
            </div>
          </div>
        </div>
      </div>
    </header>
    <div id="main" role="main">
      <div class="container">
          <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
        <footer>
          <%= render 'layouts/footer' %>
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>